name: qipso-uav
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.3.*
  - pytorch-cuda=12.1
  - numpy=1.26.*
  - scipy=1.13.*
  - matplotlib=3.9.*
  - pyyaml
  - tqdm
  - pip
  - pip:
      - pandas==2.2.*
